---

# Cryptoassets.core configuration for example application

# We use a SQLite database which lives in /tmp folder.
# This file is automatically created on startup.
database:
  url: sqlite:////tmp/cryptoassets.test.sqlite

# What services we use to run talk to the cryptocurrency networks.
# This will configure us to use pre-defined block.io API service
# testnet accounts for BTC and Doge (coins are worthless)
coins:
    btc:
        backend:
            class: cryptoassets.core.backend.blockio.BlockIo
            api_key: 0266-c2b6-c2c8-ee07
            pin: foobar123

