---

# Cryptoassets.core configuration for the wallet sample project

# Define sqlite database for testing
# Warning: SQLite databases are not suitable for product deploymenys
database:
  url: sqlite:////tmp/cryptoassets.test.sqlite

# What services we use to run talk to the cryptocurrency networks
coins:
    doge:
        backend:
            class: cryptoassets.core.backend.blockio.BlockIo
            # API key is to Dogetest
            api_key: 0266-c2b6-c2c8-ee07
            pin: foobar123
